---

- name: Transfer and execute a script.
  hosts: server
  remote_user: test_user
  sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=test.sh dest=/home/test_user mode=0777

     - name: Execute the script
       command: sh /home/test_user/test.sh



 # shell script for find invalid object if compile           
 #for all_objects:

#select 'ALTER '|| OBJECT_TYPE || ' ' || OWNER || '.' || OBJECT_NAME || ' COMPILE;'
  #from all_objects dob
  #where dob.owner <> 'PUBLIC'
  #and dob.object_type in ('SYNONYM','MATERIALIZED VIEW')
  #and dob.GENERATED != 'Y'
 # and dob.status='INVALID';

#for dba_objects:

#select 'ALTER '|| OBJECT_TYPE || ' ' || OWNER || '.' || OBJECT_NAME || ' COMPILE;'
  #from dba_objects dob
  #where dob.owner <> 'PUBLIC'
  #and dob.object_type in ('SYNONYM','MATERIALIZED VIEW')
  #and dob.GENERATED != 'Y'
  #and dob.status='INVALID';
