---
- hosts: all 
  gather_facts: no
  tasks:
    - name: Copying Batches to respective dir on the target server
      shell: |
         echo "exit" | sqlplus -L $UP | grep Connected > /dev/null
         if [ $? -eq 0 ]then;
	        echo "DB Connected Successfully...."
         else
            echo "There is some issue to connect to DB.."
         fi
  become: yes
  become_user: oretail
  become_method: sudo