---
- hosts: all
  gather_facts: no
  become: yes
  become_user: oretail
  become_method: sudo
  tasks:
    - name: Checking the DB connection and schema availability
      shell: |
         source /home/oretail/.profile
         echo "exit" | /u01/app/oradev/product/12.1.0.2/db/bin/sqlplus -L $UP | grep Connected > /dev/null
         if [ $? -eq 0 ];then
            echo "DB Connected Successfully...."
         else
            echo "There is some issue to connect to DB.."
         fi
      register: schema_out
      args:
        chdir: /home/oretail
    - debug: var=schema_out.stdout_lines
