---
  - name: create directory if not exist 
    file:
      path: "{{ patchdir }}"
      state: directory
      mode: 0777
    register: createdir

  - name: download package
    shell: wget -O {{ artifactID }}-{{ version }}.{{ classifier }} http://wtr-watm-artefactrepo.johnlewis.co.uk:8081/nexus/service/local/artifact/maven/redirect?r={{ repositoryID }}\&g={{ groupID }}\&a={{ artifactID }}\&v={{ version }}\&p={{ classifier }}
    args:
      chdir: /tmp
    when: createdir is success
    register: patchpkg

  - name: unzip the file
    unarchive:
      src: /tmp/{{ artifactID }}-{{ version }}.{{ classifier }}
      dest: "{{ patchdir }}"
      remote_src: yes
      mode: 0777
    when: patchpkg is success

  - name: create RMS BATCH backup directory
    shell: "{{ item }}"
    with_items:
         - rm -rf /u02/app/oretail/RMS_BATCH_BACKUP/DBPatch_bkp_`date '+%Y-%m-%d'`/*.tar
         - mkdir -p /u02/app/oretail/RMS_BATCH_BACKUP/DBPatch_bkp_`date '+%Y-%m-%d'`
    tag: RMSDB
    
  - name: create RPM BAT backup directory
    shell: "{{ item }}"
    with_items:
         - rm -rf /u01/app/rpmapp/RPMBAT_BACKUP/DBPatch_bkp_`date '+%Y-%m-%d'`/*.tar
         - mkdir -p /u01/app/rpmapp/RPMBAT_BACKUP/DBPatch_bkp_`date '+%Y-%m-%d'`
    tag: RPMAPP

  - name: Take RMS_BATCH backup before apply DB vendor patch 
    shell: tar --exclude='RMS_BATCH/JLCUSTOM' -pcvf /u02/app/oretail/RMS_BATCH_BACKUP/DBPatch_bkp_`date '+%Y-%m-%d'`/rmsbatch_{{ month }}.tar RMS_BATCH
    args:
      chdir: /u02/app/oretail
    register: dbpatch_bkp
    tag: RMSDB
  - debug: var=dbpatch_bkp.stderr_lines
  
  - name: Take rpmbat backup before apply DB vendor patch 
    shell: tar -pcvf /u01/app/rpmapp/RPMBAT_BACKUP/DBPatch_bkp_`date '+%Y-%m-%d'`/rpmbat_{{ month }}.tar rpmbat
    args:
      chdir: /u01/app/rpmapp
    register: dbpatch_bkp
    tag: RPMAPP
  - debug: var=dbpatch_bkp.stderr_lines
  
  - name: check if manifest.csv file exists
    stat: 
      path: "{{ patchdir }}/manifest.csv"
    register: result
  
  - name: apply patch from level 1st directory
    shell: source /home/oretail/batch.profile && {{ retail_home }}/orpatch apply -s {{ patchdir }}
    args: 
      chdir: "{{ retail_home }}"
    register: orpatch_1st
    when: result.stat.exists == true
  - debug: var=orpatch_1st.stdout_lines
  
  - name: apply patch from level 2nd directory
    shell: source /home/oretail/batch.profile && {{ retail_home }}/orpatch apply -s {{ patchdir }}/{{ patch_num }}
    args: 
      chdir: "{{ retail_home }}"
    register: orpatch_2nd
    when: result.stat.exists == false
  - debug: var=orpatch_2nd.stdout_lines
  
  - name: List the installed patches and its status
    shell: source /home/oretail/batch.profile && {{ retail_home }}/orpatch lsinventory
    args:
      chdir: "{{ retail_home }}"
      #creates: "{{ retail_home }}"
    register: orpatch_status
  - debug: var=orpatch_status.stdout_lines
