---
  - name: create directory if not exist 
    file:
      path: "{{ patchdir }}"
      state: directory
      mode: 0777
    register: createdir

  - name: download package
    shell: wget -O {{ artifactID }}-{{ version }}.{{ classifier }} http://wtr-watm-artefactrepo.johnlewis.co.uk:8081/nexus/service/local/artifact/maven/redirect?r={{ repositoryID }}\&g={{ groupID }}\&a={{ artifactID }}\&v={{ version }}\&p={{ classifier }}
    args:
      chdir: /tmp
    when: createdir is success
    register: patchpkg

  - name: unzip the file
    unarchive:
      src: /tmp/{{ artifactID }}-{{ version }}.{{ classifier }}
      dest: "{{ patchdir }}"
      remote_src: yes
      mode: 0777
    when: patchpkg is success
 
  - name: create backup directory
    shell: mkdir -p "{{ staging_base}}"/DBPatch_bkp_`date '+%Y-%m-%d'`

  - name: Take backup before DB vendor patch apply
    shell: tar -pcvf /home/oretail/JL_Automation_staging/db_patch/DBPatch_bkp_`date '+%Y-%m-%d'`/rmsbatch_AprilA.tar /u02/app/oretail/RMS_BATCH --exclude='./RMS_BATCH/JLCUSTOM'
   #shell: tar -pcvf "{{ staging_base}}"/DBPatch_bkp_`date '+%Y-%m-%d'`/rmsbatch_{{ month }}.tar /RMS_BATCH --exclude='./RMS_BATCH/JLCUSTOM'
   
  - name: moving tar file into RMSBATCH
    copy: 
      src: "{{ staging_base}}/DBPatch_bkp_`date '+%Y-%m-%d'`/rmsbatch_{{ month }}.tar"
      dest: /u02/app/oretail/RMS_BATCH
      remote_src: yes
  - name: apply patch
    shell: orpatch apply -s "{{ patchdir }}"
    args: 
      chdir: "{{ retail_home }}"
      creates: "{{ retail_home }}"
    register: orpatch
  - debug:
      msg: "patch has been applied succesfully"
    when: orpatch.rc == 0
