---
  - name: create directory if not exist 
    file:
      path: "{{ patchdir }}"
      state: directory
      mode: 0777
    register: createdir
    tags: "{{ application }}"

  - name: download package
    shell: wget -O {{ artifactID }}-{{ version }}.{{ classifier }} http://wtr-watm-artefactrepo.johnlewis.co.uk:8081/nexus/service/local/artifact/maven/redirect?r={{ repositoryID }}\&g={{ groupID }}\&a={{ artifactID }}\&v={{ version }}\&p={{ classifier }}
    args:
      chdir: /tmp
    when: createdir is success
    register: patchpkg
    tags: "{{ application }}"

  - name: unzip the file
    unarchive:
      src: /tmp/{{ artifactID }}-{{ version }}.{{ classifier }}
      dest: "{{ patchdir }}"
      remote_src: yes
      mode: 0777
    when: patchpkg is success
    tags: "{{ application }}"

  - name: create RMS_BATCH backup directory
    shell: "{{ item }}"
    with_items:
         - rm -rf /staging/deploys/Monthly_Release/RMS_patches/`date '+%Y-%m-%d'`/*.tar
         - mkdir -p /staging/deploys/Monthly_Release/RMS_patches/`date '+%Y-%m-%d'`
    tags: [ RMSDB, live_env ]
    
  - name: create RPM_BAT backup directory
    shell: "{{ item }}"
    with_items:
         - rm -rf /staging/deploys/Monthly_Release/RPM_patches/`date '+%Y-%m-%d'`/*.tar
         - mkdir -p /staging/deploys/Monthly_Release/RPM_patches/`date '+%Y-%m-%d'`
    tags: [ RPMAPP, live_env ]

  - name: Take RMS_BATCH backup before apply DB vendor patch 
    shell: "{{ item }}"
    with_items:
         - tar --exclude='RMS_BATCH/JLCUSTOM' -pcvf /staging/deploys/Monthly_Release/RMS_patches/`date '+%Y-%m-%d'`/rmsbatch.tar RMS_BATCH
         - chmod -R 777 /staging/deploys/Monthly_Release/RMS_patches
    args:
      chdir: /u02/app/oretail
    register: dbpatch_bkp
    tags: [ RMSDB, live_env ]
  - debug: var=dbpatch_bkp.stderr_lines
  
  - name: Take rpmbat backup before apply DB vendor patch
    shell: "{{ item }}"
    with_items:
         - tar -pcvf /staging/deploys/Monthly_Release/RPM_patches/`date '+%Y-%m-%d'`/rpmbat.tar rpmbat
         - chmod -R 777 /staging/deploys/Monthly_Release/RPM_patches
    args:
      chdir: /u01/app/rpmapp
    register: dbpatch_bkp
    tags: [ RPMAPP, live_env ]
  - debug: var=dbpatch_bkp.stderr_lines
  
  - name: check if manifest.csv file exists
    stat: 
      path: "{{ patchdir }}/manifest.csv"
    register: result
    tags: "{{ application }}"
  
  - name: Apply "{{ application }}" patch from level 1st directory
    shell: source /home/{{ appuser }}/batch.profile && {{ retail_home }}/orpatch apply -s {{ patchdir }}
    args: 
      chdir: "{{ retail_home }}"
    register: orpatch_1st
    when: result.stat.exists == true
    tags: "{{ application }}"
  - debug: 
      var: orpatch_1st.stdout_lines
    tags: "{{ application }}"
   
  - name: Apply "{{ application }}" patch from level 2nd directory
    shell: source /home/{{ appuser }}/batch.profile && {{ retail_home }}/orpatch apply -s {{ patchdir }}/{{ patch_num }}
    args: 
      chdir: "{{ retail_home }}"
    register: orpatch_2nd
    when: result.stat.exists == false
    tags: "{{ application }}"
  - debug: 
      var: orpatch_2nd.stdout_lines
    tags: "{{ application }}"
  
  - name: List the installed patches in "{{ application }}" and its status
    shell: source /home/{{ appuser }}/batch.profile && {{ retail_home }}/orpatch lsinventory
    args:
      chdir: "{{ retail_home }}"
    register: orpatch_status
    tags: "{{ application }}"
  - debug: 
      var: orpatch_status.stdout_lines
    tags: "{{ application }}"
