---
- name: Download artifacts
  maven_artifact:
        group_id: oracle
        artifact_id: ojdbc6
        version: 11.2.0.3.0
        repository_url: 'http://wtr-watm-artefactrepo.johnlewis.co.uk:8081/nexus/service/local/repositories/JLP-Pioneer-Releases/'
        dest: /tmp/

