---
# tasks file for oracle
- name: Create MUA backup directory
  shell: "{{ item }}"
  with_items:
       - rm -rf /staging/deploys/Monthly_Release/MUA/`date '+%Y-%m-%d'`/*.tar
       - mkdir -p /staging/deploys/Monthly_Release/MUA/`date '+%Y-%m-%d'`

- name: Take Middleware dir backup before MUA deployment
  shell: "{{ item }}"
  with_items:
       - tar -pcvf /staging/deploys/Monthly_Release/MUA/`date '+%Y-%m-%d'`/MUA_middleware.tar Middleware
       - chmod -R 777 /staging/deploys/Monthly_Release/batches
  args:
    chdir: /u01/app/{{ appuser }}/Oracle
  register: mua_bkp
- debug: var=mua_bkp.stdout_lines
