---
 - name: create directory 
   file: dest={{ destDir }} mode=755 state=directory
   register: createdir

 - name: Copy sql files to staging directory
   template: src=main.sql dest={{ destDir }}/main.sql mode=755
   when: createdir is success
   register: copyfile

 - name: Copy sql files to staging directory
   template: src=RIB_TOPIC_CHECK.sql dest={{ destDir }}/RIB_TOPIC_CHECK.sql mode=755
   when: createdir is success
   register: copyfile
   
 - name: connect to sql db
   shell: source /home/oretail/.profile && sqlplus $UP @{{ destDir }}/main.sql
   
 - name: Send e-mail to a bunch of users, attaching files
   mail:
     host: mcms.johnlewis.co.uk
     port: 25
     subject: Verify RIB topics & MF Queues
     body: Hello, This is an alert to verify the RIB topics and MF Queues status, Please find the attachment and take necessary action..
     from: gayathri.modi@johnlewis.co.uk
     to:
     - monosij.maitra@johnlewis.co.uk
     - gayathri.modi@johnlewis.co.uk
     - suman.ghorui@johnlewis.co.uk
     attach: /home/oretail/pre_check_scripts/table_count.log