---
 - name: Connecting to sql DB and executing rep_sql_deploy.sh file.
   shell: sh rep_sql_deploy.sh
   args:
     chdir: /home/oretail
   register: deploy_result
 - debug: var=deploy_result.stdout_lines
