---
 - name: Copying tempalte files to destination dir on the target server
   shell: |
      if [ -f "templates.txt" ];then
      for i in `cat templates.txt`
      do
      file=`echo $i`
      cp $file /u02/app/oretail/RMS_BATCH/JLCUSTOM/MSUP_DIR
   args:
     chdir: "{{ Staging }}"
   register: batresult
   
 - debug: var=batresult.stdout_lines
