---
 - name: Copying tempalte files to destination dir on the target server
   shell: |
      if [ -f "{{ Staging }}/templates.txt" ];then
      for i in `cat {{ Staging }}/templates.txt`
      do
      file=`echo $i`
      echo $file
      echo $i
      #chmod 755 $file
      cp {{ msupdir }}/$file {{ msupdir }}/"${file}_`date +%Y-%m-%d`"
      cp -f {{ Staging }}/$file {{ msupdir }}
      done
      fi
   args:
     chdir: {{ msupdir }}
   register: templateresult
   
 - debug: var=templateresult.stdout_lines
