---
 - name: Check if Staging directory exists
   stat:
    path: "{{ Staging }}"
   register: stage
 
 - name: If exists 
   debug:
     msg: "staging directory already existed"
   when: stage.stat.exists
 
 - name: If not exists
   file:
     path: "{{ Staging }}"
     state: directory
     mode: 0755
   when: stage.stat.exists == false
   tags: deploy

 - name: "Remove existing file"
   shell: rm -rf *.*
   args:
     chdir: "{{ Staging }}"
   tags: deploy
   
 - name: Copy files_extract script to dest dir
   template: src=files_extract.sh dest={{ Staging }} mode=755
   register: scriptcopy

 - name: download package into
   shell: wget -O {{ artifactID }}.{{ classifier }} http://wtr-watm-artefactrepo.johnlewis.co.uk:8081/nexus/service/local/artifact/maven/redirect?r={{ repositoryID }}\&g={{ groupID }}\&a={{ artifactID }}\&v={{ version }}\&p={{ classifier }}
   args:
     chdir: "{{ Staging }}"

- name: Extarcting release pacakge
   shell: "{{ item }}"
   with_items:
             - unzip -Z1 {{ artifactID }}-{{ version }}.{{ classifier }}  > release.txt
             - unzip -o {{ artifactID }}-{{ version }}.{{ classifier }}
   args:
     chdir: "{{ Staging }}"

 - name: Extracting files from zip and storing those to txt files
   shell: sh files_extract.sh
   args:
     chdir: "{{ Staging }}"
   when: scriptcopy is success
