---
 - name : find invalid objects if found exit from here
   shell: |
       cd "{{ staging_base }}"
       ls -A {{ staging_base }}/bat_bkp_`date '+%Y-%m-%d'` > rlb_bat.txt

       file1= "{{ staging_base }}"/rlb_bat.txt
       sed -i 's/\r//g' $file1
       for bat_name in `cat "$file1"`
       do
         VAR=$(echo $bat_name | egrep "(.ksh|.sh|.pc|.mk)$")
         if [ "$VAR" != "$bat_name" ];then
            echo "$bat_name is invalid file.Please check the file list in $file1"
            exit -1
         fi
       done
   args:
     chdir: "{{ staging_base }}"

