select * From (select 'SEEDOBJ_MFQUEUE->' MFQUEUE_TABLE , count(1) MESSAGE_NUM  from SEEDOBJ_MFQUEUE union all
select 'STORE_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from STORE_MFQUEUE union all
select 'BANNER_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from BANNER_MFQUEUE union all
select 'CODES_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from CODES_MFQUEUE union all
select 'WH_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from WH_MFQUEUE union all
select 'SUPPLIER_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from SUPPLIER_MFQUEUE union all
select 'MERCHHIER_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from MERCHHIER_MFQUEUE union all
select 'DIFFGRP_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from DIFFGRP_MFQUEUE union all
select 'UDA_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from UDA_MFQUEUE union all
select 'DIFFID_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from DIFFID_MFQUEUE union all
select 'ITEM_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from ITEM_MFQUEUE union all
select 'ITEMLOC_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from ITEMLOC_MFQUEUE union all
select 'WOIN_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from WOIN_MFQUEUE union all
select 'TSF_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from TSF_MFQUEUE union all
select 'ORDER_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from ORDER_MFQUEUE union all
select 'RTVREQ_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from RTVREQ_MFQUEUE union all
select 'DELIVERY_SLOT_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from DELIVERY_SLOT_MFQUEUE union all
select 'ALLOC_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from ALLOC_MFQUEUE union all
select 'RUA_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from RUA_MFQUEUE union all
select 'WOOUT_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from WOOUT_MFQUEUE union all
select 'PARTNER_MFQUEUE->'  MFQUEUE_TABLE, count(1) MESSAGE_NUM from PARTNER_MFQUEUE) order by MESSAGE_NUM desc ;