---
 - name: create directory 
   file: dest={{ destDir }} mode=755 state=directory
   register: createdir

 - name: Copy sql files to staging directory
   template: src=main.sql dest={{ destDir }}/main.sql mode=755
   when: createdir is success
   register: copyfile

   
 - name: Copy sql files to staging directory
   template: src=MFQUEUE_CHECK.sql dest={{ destDir }}/MFQUEUE_CHECK.sql mode=755
   when: createdir is success
   register: copyfile
   
 - name: Copy sql files to staging directory
   template: src=RIB_TOPIC_CHECK.sql dest={{ destDir }}/RIB_TOPIC_CHECK.sql mode=755
   when: createdir is success
   register: copyfile
   
 - name: connect to sql db
   shell: source /home/oretail/.profile && sqlplus $UP @{{ destDir }}/main.sql
