---
 - name: Create directory if not exists
   file:
     path: "{{ form_file_path }}"
     state: directory
     mode: 0755
   register: createdir

 - name: Clean files dir before download package
   shell: rm -rf *.*
   args:
     chdir: "{{ form_file_path }}"

 - name: Copy files_extract script to dest dir
   template: src=files_extract.sh dest={{ form_file_path }} mode=755
   register: scriptcopy

 - name: download package
   shell: wget -O {{ artifactID }}-{{ version }}.{{ classifier }} http://wtr-watm-artefactrepo.johnlewis.co.uk:8081/nexus/service/local/artifact/maven/redirect?r={{ repositoryID }}\&g={{ groupID }}\&a={{ artifactID }}\&v={{ version }}\&p={{ classifier }}
   args:
     chdir: "{{ form_file_path }}"
   when: createdir is success
   register: formspkg
   
 - name: Extarcting forms pacakge
   shell: "{{ item }}"
   with_items:
             - unzip -Z1 {{ artifactID }}-{{ version }}.{{ classifier }} > release.txt
             - unzip -o {{ artifactID }}-{{ version }}.{{ classifier }}
   args:
     chdir: "{{ form_file_path }}" 
   when: formspkg is success

 - name: Extracting files from zip and storing those to txt files
   shell: sh files_extract.sh
   args:
     chdir: "{{ form_file_path }}"
   when: scriptcopy is success 
 
