---
 - name: Remove xauthlist file if exist
   shell: "{{ item }}"
   with_items:
             - rm -rf xauthlist.txt
   args:
     chdir: /JL_Automation_Staging/

 - name: display xauth list
   shell: xauth list| awk '{print "xauth add "$1" "$2" "$3}' > /JL_Automation_Staging/xauthlist.txt
   register: Display
 - debug: var=Display.stdout_lines
   
 - name: run script with rmsapp user
   shell: "{{ item }}"
   with_items:
             - infile=$(awk -v "line=$Line" '/unix:10/{print}' /JL_Automation_Staging/xauthlist.txt)
             - export DISPLAY=localhost:10.0
   register: DISPLAY
 - debug:
     msg: "localhost10.0"

  

