---
 - name: connecting to sql db
   shell: source /home/oretail/.profile && /home/oretail/sql_deploy.ksh
   register: deploy_result
   tags: deploy
 - debug: var=deploy_result.stdout_lines  
   
 - name: Send e-mail to a bunch of users, attaching files
   mail:
     host: mcms.johnlewis.co.uk
     port: 25
     subject: Verify the logs of DB objects - Execution
     body: Hello, This is an alert to verify the logs, Please find the attachment and take necessary action..
     from: ramana-alladu.reddy@johnlewis.co.uk
     to:
     - ravindra.reddy@johnlewis.co.uk
     attach: 
     - /tmp/logs/rms_deploy.log
     - /tmp/logs/intr_Stg_deploy.log
   tags: deploy
   
 - name: connecting to sql db
   shell: source /home/oretail/.profile && /home/oretail/sql_rollback.ksh
   register: rollback_result
   tags: rollback
 - debug: var=rollback_result.stdout_lines
   
 - name: Send e-mail to a bunch of users, attaching files
   mail:
     host: mcms.johnlewis.co.uk
     port: 25
     subject: Verify the logs of DB Objects - Rollback
     body: Hello, This is an alert to verify the logs, Please find the attachment and take necessary action..
     from: ramana-alladu.reddy@johnlewis.co.uk
     to:
     - ravindra.reddy@johnlewis.co.uk
     attach:
     - /tmp/logs/rms_rollback.log
     - /tmp/logs/intr_stg_rollback.log
   tags: rollback
